steps:
  - command: |
      python3 -m venv myenv
      source myenv/bin/activate
      pip install -r requirements.txt
      flake8 .
      black . --check
      python3 -m pytest
      label: ":virtualenv: Setup virtual environment"
